name: Auto Edit Text

on:
  schedule:
- cron: '* * * * *'  # Every minute
  workflow_dispatch:

jobs:
  auto-edit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Overwrite data.txt with Testing + random number
        run: |
          RANDOM_NUM=$((10000 + RANDOM % 90000))  # Ensures 5-digit number
          echo "Lustra$RANDOM_NUM" > data.txt

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data.txt
          git commit -m "Auto update with Testing$RANDOM_NUM" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
